site_name: BiliResp
site_description: Utilities for parsing RESP outputs, fitting ESP charges, and validating dipoles.
site_author: E. Mainas

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Workflows:
      - Linear ESP Solver: workflows/linear-esp-solver.md
      - Dipole Cross-Validation: workflows/dipole-cross-validation.md

theme:
  name: mkdocs
